x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  postgres:
    restart: "unless-stopped"
    build:
      context: ./
      dockerfile: Dockerfile.postgres
      args:
        - DOCKER_TAG=${PG_DOCKER_TAG:-16-bookworm}
    stop_grace_period: 1m
    image: postgres:local
    pull_policy: build
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=eranode
      - CALL_TRACES=${CALL_TRACES:-false}
      - PG_SNAPSHOT=${PG_SNAPSHOT:-}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      start_period: 5s
      interval: 10s
      timeout: 5s
    volumes:
      - ./load-snapshot.sh:/docker-entrypoint-initdb.d/load-snapshot.sh
      - erapg-data:/var/lib/postgresql/data/
    command: postgres ${PG_PARAMS}

volumes:
  eranode-data:
  erapg-data:
